markdown: GFM
#theme: minima
#theme: jekyll-theme-minimal
remote_theme: pages-themes/dinky@v0.2.0
#remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
# https://github.com/pages-themes/slate
#remote_theme: pages-themes/slate@v0.2.0
#remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
#markdown_ext: "markdown,mkdown,mkdn,mkd,md"
